import asyncio
import logging
from typing import Any, Coroutine, NoReturn

import httpx
from websockets.legacy.client import WebSocketClientProtocol

from connector import ConnectorMixin
from loxone_http_client import LoxoneAsyncHttpClient
from message import MessageHeader
from message_handler import LoxoneMessageHandlerMixin
from tokens import LoxoneToken, TokensMixin
from websocket import WebsocketMixin

_LOGGER = logging.getLogger(__name__)


class Miniserver(
    ConnectorMixin,
    TokensMixin,
    WebsocketMixin,
    LoxoneMessageHandlerMixin,
):
    def __init__(
        self,
        host: str = "",
        port: int = 80,
        user: str = "",
        password: str = "",
        visual_password: str = "",
        use_tls: bool = False,
        use_websockets=True,
    ):
        self._host = host
        self._port = port
        self._user = user
        self._password = password
        self._visual_password = visual_password or password  # Default to password
        self._use_tls = use_tls
        self._tls_check_hostname: bool = True
        self._local: bool = False

        self._http_client: LoxoneAsyncHttpClient | None = None
        self._ws: WebSocketClientProtocol | None = None
        self._ping_timeout: int = 30

        self._msInfo: tuple  # type: ignore

        self.has_token = False
        self._token = LoxoneToken()

        self._msInfo: tuple  # type: ignore
        self._public_key = ""
        self._aes_key: bytes
        self._snr: str = ""
        self._structure: dict[str, Any] = {}
        self._tls_check_hostname: bool = True

        # Token stuff
        self._salt: str = ""
        self._salt_has_expired: bool = False
        self._user_salt: str = ""

        self._key: str = ""
        self._user_salt: str = ""
        self._hash_alg: str = ""

        self._version: str = ""
        self._background_tasks: list[asyncio.Task[Any]] = []

        self.message_header: MessageHeader | None = None

    async def connect(self) -> None:
        await self._ensure_reachable()
        await self._get_public_key_and_structure_file()
        await self._open_websocket()
        self._run_in_background(self.listen_for_messages())
        self._run_in_background(self.ping_server())

        await self._generate_and_pass_key()
        self._generate_salt()
        self._token = LoxoneToken()

        ## Hier weiter mit token
        await self._acquire_token()

        # while self.websocket_is_open:
        #     await asyncio.sleep(1)

        print("Open or Close:", self.websocket_is_open)

    def _run_in_background(
        self, task: Coroutine[Any, Any, NoReturn]
    ) -> asyncio.Task[Any]:
        """Run a coroutine as a background task.

        The task will run forever, until it is cancelled, or the event loop
        terminates. If an exception occurs, it will be raised in the main task."""

        def handle_errors(task: asyncio.Task[Any]) -> None:
            try:
                """Raise any errors generated by a background task"""
                # Fetching the result of a task will cause any exceptions which
                # have occurred to be raised
                _ = task.result()
            except asyncio.CancelledError:
                _LOGGER.debug(f"Cancellling {task.get_name()}")
            except asyncio.InvalidStateError:
                _LOGGER.debug(f"InvalidStateError {task.get_name()}")
            # except Exception:
            #     raise

        _task = asyncio.create_task(task, name=task.__name__)
        # If an exception occurs in a task, it is considered done, so we add a
        # callback which can re-raise any exceptions in the context of the main
        # co-routine
        _task.add_done_callback(handle_errors)
        self._background_tasks.append(_task)
        return _task
